version: "3"
services:
  express-mysql-exploration:
    build: .
    ports:
      - "3000:3000"
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
